function timestamps = create_station_timestamps_array(HF_station_id)
%% Inputs
% HF_station_id - name of the HF station as saved by WERA config
%% Output
% timestamps - array of 72 filenames for each SORT measurements of the
% station
%
%%
    timestamps = string({...
        strcat('0000_', HF_station_id), strcat('0020_', HF_station_id),...
        strcat('0040_', HF_station_id), strcat('0100_', HF_station_id),...
        strcat('0120_', HF_station_id), strcat('0140_', HF_station_id),...
        strcat('0200_', HF_station_id), strcat('0220_', HF_station_id),...
        strcat('0240_', HF_station_id), strcat('0300_', HF_station_id),...
        strcat('0320_', HF_station_id), strcat('0340_', HF_station_id),...
        strcat('0400_', HF_station_id), strcat('0420_', HF_station_id),...
        strcat('0440_', HF_station_id), strcat('0500_', HF_station_id),...
        strcat('0520_', HF_station_id), strcat('0540_', HF_station_id),...
        strcat('0600_', HF_station_id), strcat('0620_', HF_station_id),...
        strcat('0640_', HF_station_id), strcat('0700_', HF_station_id),...
        strcat('0720_', HF_station_id), strcat('0740_', HF_station_id),...
        strcat('0800_', HF_station_id), strcat('0820_', HF_station_id),...
        strcat('0840_', HF_station_id), strcat('0900_', HF_station_id),...
        strcat('0920_', HF_station_id), strcat('0940_', HF_station_id),...
        strcat('1000_', HF_station_id), strcat('1020_', HF_station_id),...
        strcat('1040_', HF_station_id), strcat('1100_', HF_station_id),...
        strcat('1120_', HF_station_id), strcat('1140_', HF_station_id),...
        strcat('1200_', HF_station_id), strcat('1220_', HF_station_id),...
        strcat('1240_', HF_station_id), strcat('1300_', HF_station_id),...
        strcat('1320_', HF_station_id), strcat('1340_', HF_station_id),...
        strcat('1400_', HF_station_id), strcat('1420_', HF_station_id),...
        strcat('1440_', HF_station_id), strcat('1500_', HF_station_id),...
        strcat('1520_', HF_station_id), strcat('1540_', HF_station_id),...
        strcat('1600_', HF_station_id), strcat('1620_', HF_station_id),...
        strcat('1640_', HF_station_id), strcat('1700_', HF_station_id),...
        strcat('1720_', HF_station_id), strcat('1740_', HF_station_id),...
        strcat('1800_', HF_station_id), strcat('1820_', HF_station_id),...
        strcat('1840_', HF_station_id), strcat('1900_', HF_station_id),...
        strcat('1920_', HF_station_id), strcat('1940_', HF_station_id),...
        strcat('2000_', HF_station_id), strcat('2020_', HF_station_id),...
        strcat('2040_', HF_station_id), strcat('2100_', HF_station_id),...
        strcat('2120_', HF_station_id), strcat('2140_', HF_station_id),...
        strcat('2200_', HF_station_id), strcat('2220_', HF_station_id),...
        strcat('2240_', HF_station_id), strcat('2300_', HF_station_id),...
        strcat('2320_', HF_station_id), strcat('2340_', HF_station_id),...
        });
end